AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Salesforce REST API Write Lambda

Resources:
  SalesforceLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: nodejs18.x
    Properties:
      LayerName: salesforce-lib
      Description: Shared Salesforce auth and dependencies
      ContentUri: ../../layers/salesforce-lib/nodejs
      CompatibleRuntimes:
        - nodejs18.x

  SalesforceWriteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 10
      Layers:
        - !Ref SalesforceLayer
      Events:
        WriteObject:
          Type: Api
          Properties:
            Path: /{sobject}
            Method: ANY
